export INPUTRC=~/.inputrc

export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

export ZSH_AUTOSUGGEST_MANUAL_REBIND=1
export ZSH_AUTOSUGGEST_USE_ASYNC=1

export ZSH_HIGHLIGHT_MAXLENGTH=1024
export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

export DISABLE_MAGIC_FUNCTIONS=true
